### ISSUE TITLE
library version

### ISSUE THREAD

**Issue by demdecuong** [pythonlessons/Reinforcement_Learning#3]
Could you update an environment.txt for me easier to run your code. Since i got some errors below.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/minh/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/minh/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 302, in train_threading
    action, prediction = agent.act(state)
  File "main.py", line 107, in act
    prediction = self.Actor.predict(state)[0]
  File "/home/minh/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 1462, in predict
    callbacks=callbacks)
  File "/home/minh/anaconda3/lib/python3.7/site-packages/keras/engine/training_arrays.py", line 324, in predict_loop
    batch_outs = f(ins_batch)
  File "/home/minh/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "/home/minh/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable dense_1/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/dense_1/bias)
         [[{{node dense_1/BiasAdd/ReadVariableOp}}]]

**Comment by pythonlessons** [comment]
Added requirements.txt file.
